CREATE DATABASE LOCADORA
GO

USE LOCADORA;

CREATE TABLE EMPRESA(
	idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeEmpresa VARCHAR(25) NOT NULL 
);
GO

CREATE TABLE CLIENTE(
	idCliente SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeCliente VARCHAR(25) NOT NULL 
);
GO

CREATE TABLE MARCA(
	idMarca SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeMARCA VARCHAR(25) NOT NULL 
);
GO

CREATE TABLE MODELO(
	idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idMarca SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
	nomeModelo VARCHAR(25) NOT NULL 
);
GO

CREATE TABLE VEICULO(
	idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
	idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
	PLACA CHAR(8) NOT NULL UNIQUE
);
GO

CREATE TABLE ALUGUEL(
	idAluguel SMALLINT PRIMARY KEY IDENTITY(1,1),
	idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
	idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idCliente),
	DataAluguel DATE NOT NULL,
	DataDevol DATE NOT NULL
);
GO

SELECT * FROM ALUGUEL