USE CATALOGO;

INSERT INTO GENERO (nomeGenero)
VALUES ('ROMANCE')

INSERT INTO FILME(idGenero,tituloFilme)
VALUES (1,'RAMBO'), (1,'VINGADORES'),
	(2,'GHOST'), (2,'DIARIO DE UMA PAIXAO')



SELECT * FROM GENERO
SELECT * FROM FILME